version: 1.0.{build}
clone_script:
- cmd: |-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive
build_script:
- cmd: |-
    cd c:\projects\cubeb
    cmake .
    cmake --build . --config Debug

build:
  verbosity: minimal

